apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cometa-azurefile-sc
provisioner: file.csi.azure.com  # Use "kubernetes.io/azure-file" for AKS versions < 1.21
allowVolumeExpansion: true
reclaimPolicy: Retain

mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=472
  - gid=472
parameters:
  skuName: Premium_LRS 