apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cometa-azure-disk-db-sc
provisioner: disk.csi.azure.com
parameters:
  skuname: Premium_LRS  # Or StandardSSD_LRS for cost-efficiency
  kind: Managed
  cachingMode: None     # "None" is safest for DB, avoids write caching issues
  fsType: ext4
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
