apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cometa-db-volume-claim-disk
  namespace: cometa
spec:
  accessModes:
    - ReadWriteOnce # Match the PV access mode
  resources:
    requests:
      storage: 80Gi # Request 80GB of storage
  storageClassName: cometa-azure-disk-db-sc # Match the StorageClass name
  