version: '3.8'

services:
  
  selenoid:
    # Please use ./selenoid/deploy_selenoid.sh to create necessary files of Selenoid
    image: aerokube/selenoid:1.11.2
    container_name: cometa_selenoid
    logging:
      driver: json-file
    ports:
      - 4444:4444
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend/selenoid/:/etc/selenoid/:ro
      - ./data/cometa/videos:/opt/selenoid/video
    environment:
      TZ: Europe/Berlin
      OVERRIDE_VIDEO_OUTPUT_DIR: ${PWD}/data/cometa/videos
    networks:
      - testing
    restart: always
    # entrypoint with limit on browser executions to CPU-2 or Defaulting to 2 if number is less then 2
    entrypoint: sh -c "LIMIT=$$(($$(nproc)-2))  && LIMIT=$$((LIMIT > 2 ? $$LIMIT:2)) && /usr/bin/selenoid \
      -listen :4444 \
      -conf /etc/selenoid/browsers.json \
      -video-output-dir /opt/selenoid/video \
      -log-output-dir /opt/selenoid/logs \
      -container-network cometa_testing \
      -limit $$LIMIT"

networks:
  testing:
    driver: "bridge"

volumes:
  redis_data: