services:
  db:
    container_name: cometa_postgres
    image: postgres:12.1
    volumes:
      - ./backend:/code
      - ./backend/db_data:/var/lib/postgresql/data
    expose:
      - "5532"
    networks:
     - testing
    restart: always

  django:
    container_name: cometa_django
    image: python:3.9
    logging:
      driver: json-file
    command: bash start.sh -d
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/cometa:/data:rw
      - ./data/cometa/screenshots:/data/screenshots
      - ./data/cometa/videos:/data/videos
      - ./data/cometa/pdf:/data/pdf
      - ./data/cometa/downloads:/data/downloads:rw
      - ./data/cometa/uploads:/data/uploads:rw
      - ./data/department_data:/data/department_data:rw
      - ./data/cometa/config:/code/config:rw
      - ./data/django/migrations:/opt/code/migrations:rw
      - ./data/django/logs:/opt/code/logs:rw
      - ./data/django/clamav:/var/lib/clamav:rw
      - ./backend:/code
      - ./backend/src:/opt/code:rw
    working_dir: /opt/code
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=dev
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - behave:cometabehave.local
    networks:
     - testing
    restart: always

  behave:
    container_name: cometa_behave
    image: python:3.11
    logging:
      driver: json-file
    ports:
      - "8001:8001"
    depends_on:
      redis:
        condition: service_healthy
      django:
        condition: service_healthy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/cometa/screenshots:/data/screenshots
      - ./data/cometa/downloads:/data/test/downloads
      - ./data/cometa/uploads:/data/test/uploads
      - ./data/cometa/videos:/data/videos
      - ./data/cometa/config:/code/config:rw
      - ./data/department_data:/data/department_data
      - ./data/redis/certs:/share/certs
      - ./data/django/logs:/opt/code/logs
      - ./backend/behave:/opt/code:rw
      - ./backend:/code
    command: "/opt/code/behave_django/entry.sh"
    # command:     sleep infinity
    working_dir: /opt/code/behave_django
    environment:
      PYTHONUNBUFFERED: 1
    networks:
     - testing
    restart: always


  ws:
    container_name: cometa_socket
    image: node:14
    working_dir: /home/node/app
    logging:
      driver: json-file
    environment:
      - NODE_ENV=development
      - NPM_CONFIG_LOGLEVEL=info
    volumes:
      - ./backend/ws-server:/home/node/app:rw
    ports:
      - "3001:3001"
    command: "npm run-script test"
    networks:
     - testing
    restart: always

  selenoid:
    # Please use ./selenoid/deploy_selenoid.sh to create necessary files of Selenoid
    image: aerokube/selenoid:1.11.2
    container_name: cometa_selenoid
    logging:
      driver: json-file
    ports:
      - 4444:4444
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend/selenoid/:/etc/selenoid/:rw
      - ./data/cometa/config/images:/code/config/images:rw
      - ./data/cometa/videos:/opt/selenoid/video
    environment:
      TZ: Europe/Berlin
      OVERRIDE_VIDEO_OUTPUT_DIR: ${PWD}/data/cometa/videos
    networks:
      - testing
    restart: always
    entrypoint: sh /etc/selenoid/start.sh

  novnc:
    container_name: cometa_novnc
    build: 
      context: noVNC  # Build context, specifying the current directory
      dockerfile: Dockerfile  # Reference to the Dockerfile
    working_dir: /home/cometa/noVNC
    command: ./utils/novnc_proxy --listen 80
    expose:
      - 80
    volumes:
      - ./noVNC:/home/cometa/noVNC
    ports:
      - 4088:80
    networks:
      - testing
    restart: always

  crontab:
    image: cometa/scheduler:latest
    container_name: cometa_crontab
    environment:
      CRONTAB_SERVER_URL: "crontab"
      CRONTAB_SERVER_PORT: "8080"
      SCHEDULER_HOST: "crontab"
      SCHEDULER_PORT: "8080"
      DEBUG_LEVEL: 10
    # volumes:
    #   - ./scheduler:/app:rw
    depends_on:
      django:
        condition: service_healthy
    networks:
      - testing
    restart: always

  apache:
    image: "httpd:2.4.48"
    container_name: cometa_front
    volumes:
      - ./:/code
      - ./front/apache-conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./front/apache-conf/openidc.conf_local:/usr/local/apache2/conf/openidc.conf
      - ./front/apache-conf/paths.conf:/usr/local/apache2/conf/paths.conf
      - ./front/apache-conf/mod_auth_openidc.so:/usr/local/apache2/modules/mod_auth_openidc.so
      - ./data/cometa/screenshots:/screenshots
    working_dir: /code/front
    ports:
      - "443:443"
      - "4200:4200"
    command: bash /code/front/start.sh openidc basic angular compile
    # command: bash /code/start.sh compile 
    environment:
      - DJANGO_SERVER_URL=django
      - DJANGO_SERVER_PORT=8000
      - SOCKET_SERVER_URL=ws
      - SOCKET_SERVER_PORT=3001
      - SELENOID_SERVER_URL=selenoid
      - SELENOID_SERVER_PORT=4444
      - NOVNC_SERVER_URL=novnc
      - NOVNC_SERVER_PORT=8080

    networks:
      - testing
    restart: always
    
  redis:
    image: redis:7.2.0-alpine
    container_name: cometa_redis
    volumes:
      - redis_data:/data
    networks:
      - testing
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    restart: always

networks:
  testing:
    driver: "bridge"

volumes:
  redis_data:
