version: '3'

services:
  db:
    container_name: cometa_postgres
    image: postgres:12.1
    volumes:
      - ./backend:/code
      - ./backend/db_data:/var/lib/postgresql/data
    expose:
      - "5532"
    networks:
     - testing
    restart: always

  django:
    container_name: cometa_django
    image: python:3.9
    logging:
      driver: json-file
    command: bash start.sh
    volumes:
      - /data/cometa/screenshots:/code/behave/screenshots
      - /data/cometa/videos:/code/behave/videos
      - /data/cometa/pdf:/code/behave/pdf
      - /data/cometa/downloads:/code/behave/downloads
      - ./backend:/code
      - ./backend/src:/opt/code:rw
      - "./backend/crontabs/cometa_django_crontab:/etc/cron.d/crontab"
    working_dir: /opt/code
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - behave:cometabehave.local
    networks:
     - testing
    restart: always

  behave:
    container_name: cometa_behave
    image: python:3.9
    logging:
      driver: json-file
    expose:
      - "8001"
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - /data/cometa/screenshots:/opt/code/screenshots
      - /data/cometa/videos:/opt/code/videos
      - /data/cometa/pdf:/code/behave/pdf
      - /data/cometa/downloads:/code/behave/downloads
      - ./backend/behave:/opt/code:rw
      - ./backend:/code
      - "./backend/behave/schedules/crontab:/etc/cron.d/crontab"
    command: "/code/docker/build/behave/entry.sh"
    working_dir: /opt/code/behave_django
    environment:
      PYTHONUNBUFFERED: 1
      <<: *browser-limit
    networks:
     - testing
    restart: always

  ws:
    container_name: cometa_socket
    image: node:14
    working_dir: /home/node/app
    logging:
      driver: json-file
    environment:
      - NODE_ENV=production
      - NPM_CONFIG_LOGLEVEL=info
    volumes:
      - ./backend/ws-server:/home/node/app:rw
    ports:
      - "3001:3001"
    command: "npm run-script start"
    networks:
     - testing
    restart: always

  selenoid:
    # Please use ./selenoid/deploy_selenoid.sh to create necessary files of Selenoid
    image: aerokube/selenoid:1.10.12
    container_name: cometa_selenoid
    logging:
      driver: json-file
    ports:
      - 4444:4444
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend/selenoid/:/etc/selenoid/:ro
      - /data/cometa/videos:/opt/selenoid/video
    environment:
      TZ: Europe/Berlin
      OVERRIDE_VIDEO_OUTPUT_DIR: /data/cometa/videos
    networks:
      - testing
    restart: always
    # entrypoint with limit on browser executions to CPU-2 or Defaulting to 2 if number is less then 2
    entrypoint: sh -c "LIMIT=$$(($$(nproc)-2))  && LIMIT=$$((LIMIT > 2 ? $$LIMIT:2)) && /usr/bin/selenoid \
      -listen :4444 \
      -conf /etc/selenoid/browsers.json \
      -video-output-dir /opt/selenoid/video \
      -log-output-dir /opt/selenoid/logs \
      -container-network cometa_testing \
      -limit $$LIMIT"

  novnc:
    image: cometa/novnc:1.0
    container_name: cometa_novnc
    networks:
      - testing
    restart: always

  apache:
    image: "httpd:2.4.48"
    container_name: cometa_front
    volumes:
      - ./front/:/code
      - ./front/apache-conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./front/apache-conf/openidc.conf_<server>:/usr/local/apache2/conf/openidc.conf
      - ./front/apache-conf/paths.conf:/usr/local/apache2/conf/paths.conf
      - ./front/apache-conf/mod_auth_openidc.so:/usr/local/apache2/modules/mod_auth_openidc.so
      - /data/cometa/screenshots:/screenshots
    working_dir: /code
    privileged: true
    ports:
      - "<outside_port>:80"
      - "443:443"
      - "4200:4200"
    command: bash /code/start.sh openidc basic angular compile
    networks:
      - testing
    restart: always

  redis:
    image: redis:7.2.0-alpine
    container_name: cometa_redis
    volumes:
      - redis_data:/data
    networks:
      - testing
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    restart: always

networks:
  testing:
    driver: "bridge"

volumes:
  redis_data: