services:

  apache:
    image: "cometa_front_image"
    container_name: cometa_front_image
    working_dir: /code/front
    privileged: true
    ports:
      - "8087:80"
    command: bash /code/front/start_server.sh
    networks:
      - test
    restart: always

networks:
  test:
    driver: "bridge"

volumes:
  redis_data: