apiVersion: v1
kind: Pod
metadata:
  name: cometa-behave-pod
  labels:
    app: cometa-behave-pod
spec:
  containers:
  - name: cometa-behave-container
    image: python:3.9
    ports:
    - containerPort: 8001
    volumeMounts:
    - name: cometa-volume
      mountPath: /opt/code/screenshots
      subPath: ./data/cometa/screenshots
    - name: cometa-volume
      mountPath: /opt/code/videos
      subPath: ./data/cometa/videos
    - name: cometa-volume
      mountPath: /code/behave/pdf
      subPath: ./data/cometa/pdf
    - name: cometa-volume
      mountPath: /code/behave/downloads
      subPath: ./data/cometa/downloads
    - name: cometa-volume
      mountPath: /opt/code
      subPath: ./backend/behave
    - name: cometa-volume
      mountPath: /code
      subPath: ./backend
    - name: cometa-volume
      mountPath: /etc/cron.d/crontab
      subPath: ./backend/behave/schedules/crontab

    workingDir: /opt/code/behave_django
    command: ["/bin/sh", "-c", "/code/docker/build/behave/entry.sh"]
    env:
    - name: PYTHONUNBUFFERED
      value: "1"
    - name: REDIS_SERVER
      value: "cometa-redis-service"
    - name: REDIS_PORT
      value: "6379"
      
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
      requests:
        cpu: "1"
        memory: "1Gi"
    
  volumes:
    - name: cometa-volume
      hostPath:
        path: "/cometa"