apiVersion: v1
kind: Service
metadata:
  name: cometa-front-service
spec:
  selector:
    app: cometa-front-pod
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
    - name: dev-mod
      protocol: TCP
      port: 4200
      targetPort: 4200