apiVersion: v1
kind: Pod
metadata:
  name: cometa-postgres-pod
  labels:
    app: cometa-postgres-pod
spec:
  containers:
  - name: postgres
    image: postgres:12.1
    ports:
    - containerPort: 5432