apiVersion: v1
kind: Pod
metadata:
  name: cometa-redis-pod
  labels:
    app: cometa-redis-pod
spec:
  containers:
  - name: redis
    image: redis:7.2.0-alpine
    ports:
      - containerPort: 6379
    volumeMounts:
      - name: cometa-volume 
        mountPath: /data
        subPath: ./data
        
    resources:
      limits:
        memory: "512Mi"
        cpu: "0.5"
    # readinessProbe:
    #   exec:
    #     command:
    #     - redis-cli
    #     - ping
    #   initialDelaySeconds: 5
    #   timeoutSeconds: 1

  volumes:
    - name: cometa-volume
      persistentVolumeClaim:
        claimName: cometa-volume-claim
        
  restartPolicy: Always
