apiVersion: v1
kind: Service
metadata:
  name: cometa-socket-service
spec:
  selector:
    app: cometa-socket-pod
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
