apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-manager
  namespace: cometa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: cometa
  name: pod-manager-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["create", "get", "list", "watch", "delete", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-manager-rolebinding
  namespace: cometa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-manager-role
subjects:
  - kind: ServiceAccount
    name: pod-manager
    namespace: cometa
