# Use Python 3.9 base image from the Docker Hub
FROM python:3.9

# Install necessary packages
RUN apt-get update && apt-get install --no-install-recommends -y \
    rsyslog \
    vim \
    jq \
    nano \
    supervisor \
    && apt-get purge -y --auto-remove exim* \
    && rm -rf /var/lib/apt/lists/*

# Update pip
RUN python -m pip install --upgrade pip

# Install Poetry via pip for security reasons
RUN pip install poetry

# Create a non-root user 'cometa' with UID 472 and GID 472
RUN groupadd -g 472 cometa && \
    useradd -u 472 -g cometa -m cometa -s /bin/bash

# Create necessary directories with appropriate ownership and permissions
RUN mkdir -p /etc/supervisor/conf.d
RUN mkdir -p /opt/code 
RUN mkdir -p /code
RUN mkdir -p /share


RUN chown -R cometa:cometa /code
RUN chown -R cometa:cometa /share
RUN chown -R cometa:cometa /opt/code
RUN chown -R cometa:cometa /home/cometa
RUN chown -R cometa:cometa /usr/local/
RUN chown -R cometa:cometa /var/log 
RUN chown -R cometa:cometa /var/run 
RUN chown -R cometa:cometa /etc/rsyslog.d
RUN chown -R cometa:cometa /etc/supervisor


RUN chmod -R 755 /code
RUN chmod -R 755 /share
RUN chmod -R 755 /opt/code
RUN chmod -R 755 /usr/local/lib/python3.9/
RUN chmod -R 755 /usr/local/bin/chardetect/

# Set the working directory
WORKDIR /code/behave

COPY --chown=cometa:cometa ./behave /opt/code
COPY --chown=cometa:cometa . /code

# Copy Python dependency files to the container with the correct user ownership
COPY --chown=cometa:cometa poetry.lock pyproject.toml /opt/code/

WORKDIR /opt/code/
# Switch to non-root user before installing packages

USER cometa
RUN chmod -R 755 /opt/code
# Configure Poetry and install dependencies without creating a virtual environment
RUN poetry config virtualenvs.create false 
RUN poetry install --no-interaction --no-ansi
# Install Behave
RUN pip install behave

# Set the entry point script, ensure it's executable
COPY --chown=cometa:cometa ./behave/entry.sh /opt/code/behave_django/entry.sh

RUN chmod +x /opt/code/behave_django/entry.sh
RUN chmod +x /opt/code/run_remote_from_django.sh

WORKDIR /opt/code/behave_django

# Finish setup, execute the entrypoint script
CMD ["entry.sh"]
