apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cometa-data-volume-claim
  namespace: cometa
spec:
  accessModes:
    - ReadWriteMany # Match the PV access mode
  resources:
    requests:
      storage: 420Gi # Request 420GB of storage
  storageClassName: cometa-azure-file-data-sc # Match the StorageClass name
  