version: "3.8"

services:

  postgres-db:
    image: postgres:15.5-alpine
    container_name: postgres-db
    restart: always
    ports:
      - "4352:5432"
    volumes:
      - ./db/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=healenium
      - POSTGRES_USER=healenium_user
      - POSTGRES_PASSWORD=YDk2nmNs4s9aCP6K
    networks:
      - cometa_testing

  healenium:
    image: healenium/hlm-backend:3.4.4
    container_name: healenium
    restart: on-failure
    ports:
      - "7878:7878"
    links:
      - postgres-db
    environment:
      - SPRING_POSTGRES_DB=healenium
      - SPRING_POSTGRES_SCHEMA=healenium
      - SPRING_POSTGRES_USER=healenium_user
      - SPRING_POSTGRES_PASSWORD=YDk2nmNs4s9aCP6K
      - SPRING_POSTGRES_DB_HOST=postgres-db
      - KEY_SELECTOR_URL=false
      - COLLECT_METRICS=true
      - FIND_ELEMENTS_AUTO_HEALING=false
      - HLM_LOG_LEVEL=info
    volumes:
      - ./screenshots/:/screenshots
      - ./logs/:/logs
    networks:
      - cometa_testing

  selector-imitator:
    image: healenium/hlm-selector-imitator:1.4
    container_name: selector-imitator
    restart: on-failure
    ports:
      - "8089:8000"
    networks:
      - cometa_testing

  hlm-proxy:
    image: healenium/hlm-proxy:1.4.0
    container_name: hlm-proxy
    restart: on-failure
    ports:
      - "8085:8085"
    environment:
      - RECOVERY_TRIES=1
      - SCORE_CAP=.6
      - HEAL_ENABLED=true
      - SELENIUM_SERVER_URL=http://88.198.116.6:4444/wd/hub
      - APPIUM_SERVER_URL=http://host.docker.internal:4723/wd/hub
      - HEALENIUM_SERVER_URL=http://localhost:7878
      - HEALENIUM_SERVICE=http://healenium:7878
      - IMITATE_SERVICE=http://selector-imitator:8089
      - HLM_LOG_LEVEL=info
    volumes:
      - ./logs/:/logs
    networks:
      - cometa_testing

  selenoid-ui:
    image: aerokube/selenoid-ui:latest-release
    restart: on-failure
    ports:
      - "8099:8080"
    command: [ "--selenoid-uri", "http://cometa_selenoid:4444" ]
    networks:
      - cometa_testing

networks:
  cometa_testing:
    external:
      name: cometa_testing
    