# create a basic configuration script for
# selected server change extension name to
# match filename
.amvara8.build-1:
  # set main variable for selected server
  variables:
 

  before_script:
    #########################################################
    # FRONTEND
    #########################################################
    # Get the version of build from front config.json
    - BUILD_VERSION=$(jq -r '.version' "$CONFIG_FILE") # Extract versions
    - echo "Build Versions -> $BUILD_VERSION"
  

  # after_script:
  #   #########################################################
  #   # FRONTEND
  #   #########################################################
    
  #   # make infra folder
  #   - docker exec cometa_front bash -c "mkdir -p /usr/local/apache2/htdocs/infra"
  #   # make a lbtest1.html file with some status info
  #   - docker exec cometa_front mv front/src/lb_test.html /usr/local/apache2/htdocs/infra/lb1test.html
     
    
  tags: # on what runners we'd like to run this job
    - build
  only: # on what branch we'd like to run this job
    refs:
      - schedules

.amvara8.build-2:

  tags: # on what runners we'd like to run this job
    - build
  only: # Indicates this job is set to run on a schedule.
    refs:
      - schedules
