# create a basic configuration script for
# selected server change extension name to
# match filename
.amvara3.prod:
  # set main variable for selected server
  variables:
    #########################################################
    # BACKEND
    #########################################################
    DEPLOY_BACKEND_FOLDER: "/home/amvara/projects/cometa"
    COMETA_DOMAIN: "prod.cometa.rocks"
    COMETA_DEBUG: "False"
    COMETA_EMAIL_HOST: 'mail.amvara.de'
    COMETA_EMAIL_USER: 'tec_dev@amvara.de'
    COMETA_EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    COMETA_EMAIL_PORT: 587
    COMETA_EMAIL_TLS: 'True'
    COMETA_PROXY_ENABLED: 'False'
    COMETA_PROXY: ''
    # limit the number of browsers to CPUs-2 ... the same for Redis Workers
    BROWSER_LIMIT: `$(($(nproc)-2))`    
    #########################################################
    # FRONTEND
    #########################################################
    DOCKER_HTTP_PORT: 8082
    DOCKER_OPENIDC_CONFIG_EXT: "amvara"
  before_script:
    #########################################################
    # FRONTEND
    #########################################################
    # remove port 443 from docker-compose since amvara servers use haproxy to loadbalance ssl requests
    - sed -i "/443:443/d" docker-compose.yml
  tags: # on what runners we'd like to run this job
    - amvara3
  only: # on what branch we'd like to run this job
    refs:
      - master