# create a basic configuration script for
# selected server change extension name to
# match filename
.amvara3.prod:
  # set main variable for selected server
  variables:
    #########################################################
    # BACKEND
    #########################################################
    DEPLOY_BACKEND_FOLDER: "/var/www/cometa"
    COMETA_DATA_FOLDER: "/data"
    COMETA_DOMAIN: "prod.cometa.rocks"
    COMETA_DEBUG: "False"
    COMETA_PROXY: ''
    #########################################################
    # FRONTEND
    #########################################################
    DOCKER_HTTP_PORT: 8082
    DOCKER_OPENIDC_CONFIG_EXT: "amvara"
  before_script:
    #########################################################
    # FRONTEND
    #########################################################
    # remove port 443 from docker-compose since amvara servers use haproxy to loadbalance ssl requests
    - sed -i "/443:443/d" docker-compose.yml
    # Replace the data path
    - sed -i 's|\.\/data|$COMETA_DATA_FOLDER|g' docker-compose.yml
    # Replace google client information
    - echo $COMETA_GOOGLE_OIDC_SECRET > $COMETA_DATA_FOLDER/front/apache2/metadata/accounts.google.com.client
    # Replace git client secret for access to git.amvara.de
    - echo $GITLAB_OIDC_SECRETS > $COMETA_DATA_FOLDER/front/apache2/metadata/git.amvara.de.client
  


  tags: # on what runners we'd like to run this job
    - amvara3
  only: # on what branch we'd like to run this job
    refs:
      - master