# create a basic configuration script for
# selected server change extension name to
# match filename
.amvara3.prod:
  # set main variable for selected server
  variables:
    #########################################################
    # BACKEND
    #########################################################
    DEPLOY_BACKEND_FOLDER: "/home/amvara/projects/cometa"
    COMETA_DOMAIN: "prod.cometa.rocks"
    COMETA_DEBUG: "False"
    COMETA_PROXY: ''
    #########################################################
    # FRONTEND
    #########################################################
    DOCKER_HTTP_PORT: 8082
    DOCKER_OPENIDC_CONFIG_EXT: "amvara"
  before_script:
    #########################################################
    # FRONTEND
    #########################################################
    # remove port 443 from docker-compose since amvara servers use haproxy to loadbalance ssl requests
    - sed -i "/443:443/d" docker-compose.yml
    
    # These changes are client specific it should not run in the all deployments 
    # Replace google client information
    - sed -i 's/@@COMETA_GOOGLE_CLIENTID@@/'$COMETA_GOOGLE_CLIENTID'/g' front/apache-conf/metadata/accounts.google.com.client
    - sed -i 's/@@COMETA_GOOGLE_SECRETKEY@@/'$COMETA_GOOGLE_SECRETKEY'/g' front/apache-conf/metadata/accounts.google.com.client
    # Replace git client secret for access to git.amvara.de
    - sed -i 's/@@GITCLIENTID@@/'$GITCLIENTID'/g' front/apache-conf/metadata/git.amvara.de.client
    - sed -i 's/@@GITCLIENTSECRET@@/'$GITCLIENTSECRET'/g' front/apache-conf/metadata/git.amvara.de.client


  tags: # on what runners we'd like to run this job
    - amvara3
  only: # on what branch we'd like to run this job
    refs:
      - master