# create a basic configuration script for
# selected server change extension name to
# match filename
.client03.prod:
  # set main variable for selected server
  variables:
    #########################################################
    # BACKEND
    #########################################################
    DEPLOY_BACKEND_FOLDER: "/opt/IBM/cometa"
    COMETA_DOMAIN: "$CLIENT_03_DOMAIN"
    COMETA_DEBUG: "False"
    COMETA_EMAIL_HOST: '$COMETA_CLIENT01_EMAIL_HOST'
    COMETA_EMAIL_USER: '$COMETA_CLIENT01_EMAIL_USER'
    COMETA_DJANGO_SECRETKEY: '$COMETA_CLIENT03_DJANGO_SECRETKEY'
    COMETA_BEHAVE_SECRETKEY: '$COMETA_CLIENT03_BEHAVE_SECRETKEY'
    COMETA_PROXY_ENABLED: 'True'
    COMETA_PROXY: '$CLIENT_03_PROXY'
    COMETA_NO_PROXY: '$CLIENT_03_NO_PROXY'
    #########################################################
    # FRONTEND
    #########################################################
    DOCKER_HTTP_PORT: 58080
    DOCKER_OPENIDC_CONFIG_EXT: "client01_int"
  before_script:
    #########################################################
    # FRONTEND
    #########################################################
    # Remove standard ports for this client, as it conflicts with other running software
    - sed -i '/443:443/d; /4200:4200/d' docker-compose.yml
    # Client uses port 58080, which is mapped to load balancer, make changes persistent for port 58080
    # - sed -i 's#/data/cometa/#./data/cometa/#g' docker-compose.yml
    - sed -i_template "s#- /data#- \./data#g" docker-compose.yml

  after_script:
    #########################################################
    # FRONTEND
    #########################################################
    
    # make infra folder
    - docker exec cometa_front bash -c "mkdir -p /usr/local/apache2/htdocs/infra"
    # make a lbtest1.html file with some status info
    - |
      docker exec cometa_front bash -c "cat <<EOF > /usr/local/apache2/htdocs/infra/lb1test.html
      <html>
        <head>
          <title>LB Test #1</title>
        </head>
        <body>
          <p>Status: OK</p>
        </body>
      </html>
      EOF
      "
  tags: # on what runners we'd like to run this job
    - cmdip-app
  only: # on what branch we'd like to run this job
    refs:
      - master
