# create a basic configuration script for
# selected server change extension name to
# match filename
.client01.int:
  # set main variable for selected server
  variables:
    #########################################################
    # BACKEND
    #########################################################
    DEPLOY_BACKEND_FOLDER: "/var/www/cometa"
    COMETA_DOMAIN: "$COMETA_CLIENT01_DOMAIN_INT"
    COMETA_DEBUG: "False"
    COMETA_EMAIL_HOST: '$COMETA_CLIENT01_EMAIL_HOST'
    COMETA_EMAIL_USER: '$COMETA_CLIENT01_EMAIL_USER'
    COMETA_PROXY_ENABLED: 'True'
    COMETA_PROXY: '$COMETA_CLIENT01_PROXY_INT'
    #########################################################
    # FRONTEND
    #########################################################
    DOCKER_HTTP_PORT: 8081
    DOCKER_OPENIDC_CONFIG_EXT: "client01_int"
    # FIXME Need to Checkon this
    COMETA_DATA_FOLDER: "/data"
  before_script:    
    #########################################################
    # FRONTEND
    #########################################################
    - sed -i 's|\.\/data|$COMETA_DATA_FOLDER|g' docker-compose.yml
    
    # Update Client01 related OIDC information
    - echo $COMETA_CLIENT01_INT_OIDC_SECRET > $COMETA_DATA_FOLDER/front/apache2/metadata/$COMETA_CLIENT01_OIDCHOST.client
    - echo $COMETA_CLIENT01_INT_OIDC_CONFIGURATION > $COMETA_DATA_FOLDER/front/apache2/metadata/$COMETA_CLIENT01_OIDCHOST.conf
    - curl https://$COMETA_CLIENT01_OIDCHOST/.well-known/openid-configuration | jq . > $COMETA_DATA_FOLDER/front/apache2/metadata/$COMETA_CLIENT01_OIDCHOST.provider

    # Replace git client secret for access to git.amvara.de
    - echo $GITLAB_OIDC_SECRETS > $COMETA_DATA_FOLDER/front/apache2/metadata/git.amvara.de.client
    - echo $GITLAB_OIDC_CONFIGURATION > $COMETA_DATA_FOLDER/front/apache2/metadata/git.amvara.de.conf
    
  after_script:
    #########################################################
    # FRONTEND
    #########################################################
    # make infra folder
    - docker exec cometa_front bash -c "mkdir -p /usr/local/apache2/htdocs/infra"
    # make a lbtest1.html file with some status info
    - |
      docker exec cometa_front bash -c "cat <<EOF > /usr/local/apache2/htdocs/infra/lbtest1.html
      <html>
        <head>
          <title>LB Test #1</title>
        </head>
        <body>
          <p>Status: OK</p>
        </body>
      </html>
      EOF
      "
  tags: # on what runners we'd like to run this job
    - sgdem0005125
  only: # on what branch we'd like to run this job
    refs:
      - stage