
networks:
  cometa_testing:
    external: true

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "3306:3306"
    networks:
      - cometa_testing

  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    networks:
      - cometa_testing

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: StrongPassword123!
    ports:
      - "1433:1433"
    networks:
      - cometa_testing

  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle_db
    environment:
      ORACLE_PASSWORD: oraclepassword
    ports:
      - "1521:1521"
      - "5500:5500"
    networks:
      - cometa_testing

  mongo:
    image: mongo:6.0
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: testdb
    ports:
      - "27017:27017"
    networks:
      - cometa_testing