version: '3.8'

services:
  mongodb:
    image: mongo:latest
    name: mongo_database
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "rootpassword"
      MONGO_INITDB_DATABASE: "organization"
    ports:
      - "27017:27017"
    volumes:
      - data_mongodb:/data/db
      - ../backend/behave/db_tests/dummy_data/mongo_inits:/tmp/data
    networks:
      - cometa_testing

volumes:
  data_mongodb:

networks:
  cometa_testing:
    external: true