services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: organization
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "3306:3306"
    volumes:
      - data_mysql:/var/lib/mysql
    networks:
      - cometa_testing

volumes:
  data_mysql:

networks:
  cometa_testing:
    external: true