apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
  namespace: cometa  # Specify the namespace
  labels:
    app: ubuntu-pod
spec:
  serviceAccountName: pod-manager
  tolerations:
  - key: "architecture"
    operator: "Equal"
    value: "amd"
    effect: "NoSchedule"


  containers:
  - name: ubuntu-container
    image: ubuntu:latest
    imagePullPolicy: Always

    command: ["/bin/bash", "-c"]
    args: ["sleep infinity"]
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
      requests:
        cpu: "500m"
        memory: "512Mi"

  nodeSelector:
    kubernetes.io/os: linux
