apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cometa-db-volume-claim
  namespace: cometa
spec:
  accessModes:
    - ReadWriteMany # Match the PV access mode
  resources:
    requests:
      storage: 80Gi # Request 500GB of storage
  storageClassName: cometa-azure-file-db-sc # Match the StorageClass name
  