# To execute this docker compose yml file use `docker compose -f docker-compose-v3-video.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker compose -f docker-compose-v3-video.yml down`
version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.20.0-20240425
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_SCREEN_WIDTH=1920
      - SE_SCREEN_HEIGHT=1080
      - SE_SCREEN_DEPTH=24

  edge:
    image: selenium/node-edge:4.20.0-20240425
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_SCREEN_WIDTH=1920
      - SE_SCREEN_HEIGHT=1080
      - SE_SCREEN_DEPTH=24
  firefox:
    image: selenium/node-firefox:4.20.0-20240425
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_SCREEN_WIDTH=1920
      - SE_SCREEN_HEIGHT=1080
      - SE_SCREEN_DEPTH=24

  chrome_video:
    image: selenium/video:0.1
    volumes:
      - /home/ubuntu/kubernetes/tanzu/cometa_code_data/data/data/cometa/videos/:/videos
    depends_on:
      - chrome
    environment:
      - DISPLAY_CONTAINER_NAME=chrome
      - SE_VIDEO_FILE_NAME=auto
      - VIDEO_EXTENSION=mkv

  edge_video:
    image: selenium/video:0.1
    volumes:
      - /home/ubuntu/kubernetes/tanzu/cometa_code_data/data/data/cometa/videos/:/videos
    depends_on:
      - edge
    environment:
      - DISPLAY_CONTAINER_NAME=edge
      - SE_VIDEO_FILE_NAME=auto
      - VIDEO_EXTENSION=mkv

  firefox_video:
    image: selenium/video:0.1
    volumes:
      - /home/ubuntu/kubernetes/tanzu/cometa_code_data/data/data/cometa/videos/:/videos
    depends_on:
      - firefox
    environment:
      - DISPLAY_CONTAINER_NAME=firefox
      - SE_VIDEO_FILE_NAME=auto
      - VIDEO_EXTENSION=mkv

  selenium-hub:
    image: selenium/hub:4.20.0-20240425
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"