# This docker file is used to create create a apache image which contains all required dependencies
# to run Cometa front container
# Intension is to reduce installation time of Cometa front
# Date v1: 08-04-2024 (Anand Kushwaha)  

# initialize base httpd image
FROM httpd:2.4.48

# author of the image
LABEL AUTHOR="COMETA ROCKS S.L."

# set a default shell
SHELL ["/bin/bash", "-c"]

# make a /code directory that will save all the git repo data
RUN mkdir /code
RUN mkdir /code/front

# set workdir to /code for compiling purposes
WORKDIR /code

COPY ./dependency-install.sh /code/front/dependency-install.sh
# make sure dependency-install.sh  has execution permissions
RUN chmod +x /code/front/dependency-install.sh 

# run /code/front/dependency-install.sh script to install prerequsite which takes time
RUN /code/front/dependency-install.sh 