# Use the specified Apache HTTPD image
FROM cometa/front:latest

COPY --chown=cometa:cometa apache-conf/httpd.conf /usr/local/apache2/conf/httpd.conf
COPY --chown=cometa:cometa apache-conf/openidc.conf_local_non_root /usr/local/apache2/conf/openidc.conf
COPY --chown=cometa:cometa apache-conf/paths.conf /usr/local/apache2/conf/paths.conf
COPY --chown=cometa:cometa apache-conf/mod_auth_openidc.so /usr/local/apache2/modules/mod_auth_openidc.so


USER cometa
# Run Apache in the foreground
CMD ["/code/front/start_pod.sh"]
